## 1.数据的导入与导出

In [1]:
import pandas as pd
import numpy as np
# 数据的导入
# 以.csv文件为例，先把目标csv文件放在项目文件夹的某一位置中，然后按照以下方式导入
df_gdp_00_24 = pd.read_csv("data/global_gdp_inflation_2000_2024.csv")    # 只需填入项目文件夹下级路径
print(df_gdp_00_24)

#数据的导出
df_gdp_00_24 = df_gdp_00_24.head(25)
df_gdp_00_24.to_csv("data/global_gdp_inflation_2000_2024(1).csv")

      Year      Country ISO3  GDP_Growth_Percent  Inflation_Percent  \
0     2001  Afghanistan  AFG           -9.431974                NaN
1     2002  Afghanistan  AFG           28.600001                NaN
2     2003  Afghanistan  AFG            8.832278                NaN
3     2004  Afghanistan  AFG            1.414118                NaN
4     2005  Afghanistan  AFG           11.229715          12.686269
...    ...          ...  ...                 ...                ...
5199  2020     Zimbabwe  ZWE           -7.816951         557.201817
5200  2021     Zimbabwe  ZWE            8.468017          98.546105
5201  2022     Zimbabwe  ZWE            6.139263         104.705171
5202  2023     Zimbabwe  ZWE            5.350869                NaN
5203  2024     Zimbabwe  ZWE            1.742395                NaN

       Data_Type          Source
0     Historical  World Bank API
1     Historical  World Bank API
2     Historical  World Bank API
3     Historical  World Bank API
4     Historical  World Bank API
...          ...             ...
5199  Historical  World Bank API
5200  Historical  World Bank API
5201  Historical  World Bank API
5202  Historical  World Bank API
5203  Historical  World Bank API

[5204 rows x 7 columns]

## 2.缺失值的处理

In [2]:
# 查看是否为缺失值的方法前面已经学过
df_2 = pd.DataFrame([[1,2,np.nan],[4,5,6],[7,None,pd.NA]],index=[1,2,3],columns=['A','B','C'])
print(df_2)
print(df_2.isna().sum())    # 这样可以查看缺失值的个数。在df里默认按照axis=0查看每列的。可以改成.sum(axis=1)

   A    B     C
1  1  2.0   NaN
2  4  5.0     6
3  7  NaN  <NA>
A    0
B    1
C    2
dtype: int64

In [3]:
# 剔除缺失值
print(df_2.dropna())    # 这样会剔除包含缺失值的行
                        # 很奇怪的一点，不输入axis参数还是默认axis=0，但是结果却是按照行来保留的，这是为什么？
# axis=0的具体含义是沿着竖轴进行操作，在df里就是沿着index，因此是一行一行地进行操作。同理，axis=1对应column

# 可以通过添加how参数来判断剔除的条件
print(df_2.dropna(how='all'))    # 只有这一行都是缺失值才把这一行剔除，默认how='any'
print(df_2.dropna(thresh=2))    # 如果至少有num个非缺失值，就保留
print(df_2.dropna(subset=['B','C']))    # 对某列进行缺失值剔除

   A    B  C
2  4  5.0  6
   A    B     C
1  1  2.0   NaN
2  4  5.0     6
3  7  NaN  <NA>
   A    B    C
1  1  2.0  NaN
2  4  5.0    6
   A    B  C
2  4  5.0  6

In [4]:
# 填充缺失值
df_gdp_00_24 = pd.read_csv("data/global_gdp_inflation_2000_2024.csv")

print(df_gdp_00_24.isna().sum())    # 这里有一些缺失值，集中在GDP增长率和通胀率这两列
# 用固定值来填充
print(df_gdp_00_24.fillna({'Inflation_Percent':'UNKNOWN'}))    # 使用字典来填充，同样可以添加键值对来对其它列进行填充
# 用合适的统计值来填充
print(df_gdp_00_24.fillna(df_gdp_00_24[['GDP_Growth_Percent']].mean()))    # 以平均值为例
# 根据缺失值附近的数据来填充
print(df_gdp_00_24.ffill())    # 用缺失值前面的相邻值填充，f是front
print(df_gdp_00_24.bfill())    # 用缺失值后面的相临值填充，b是behind

# 根据具体的情景选择具体的填充方式

Year                    0
Country                 0
ISO3                    0
GDP_Growth_Percent     44
Inflation_Percent     688
Data_Type               0
Source                  0
dtype: int64
      Year      Country ISO3  GDP_Growth_Percent Inflation_Percent  \
0     2001  Afghanistan  AFG           -9.431974           UNKNOWN
1     2002  Afghanistan  AFG           28.600001           UNKNOWN
2     2003  Afghanistan  AFG            8.832278           UNKNOWN
3     2004  Afghanistan  AFG            1.414118           UNKNOWN
4     2005  Afghanistan  AFG           11.229715         12.686269
...    ...          ...  ...                 ...               ...
5199  2020     Zimbabwe  ZWE           -7.816951        557.201817
5200  2021     Zimbabwe  ZWE            8.468017         98.546105
5201  2022     Zimbabwe  ZWE            6.139263        104.705171
5202  2023     Zimbabwe  ZWE            5.350869           UNKNOWN
5203  2024     Zimbabwe  ZWE            1.742395           UNKNOWN

       Data_Type          Source
0     Historical  World Bank API
1     Historical  World Bank API
2     Historical  World Bank API
3     Historical  World Bank API
4     Historical  World Bank API
...          ...             ...
5199  Historical  World Bank API
5200  Historical  World Bank API
5201  Historical  World Bank API
5202  Historical  World Bank API
5203  Historical  World Bank API

[5204 rows x 7 columns]
      Year      Country ISO3  GDP_Growth_Percent  Inflation_Percent  \
0     2001  Afghanistan  AFG           -9.431974                NaN
1     2002  Afghanistan  AFG           28.600001                NaN
2     2003  Afghanistan  AFG            8.832278                NaN
3     2004  Afghanistan  AFG            1.414118                NaN
4     2005  Afghanistan  AFG           11.229715          12.686269
...    ...          ...  ...                 ...                ...
5199  2020     Zimbabwe  ZWE           -7.816951         557.201817
5200  2021     Zimbabwe  ZWE            8.468017          98.546105
5201  2022     Zimbabwe  ZWE            6.139263         104.705171
5202  2023     Zimbabwe  ZWE            5.350869                NaN
5203  2024     Zimbabwe  ZWE            1.742395                NaN

       Data_Type          Source
0     Historical  World Bank API
1     Historical  World Bank API
2     Historical  World Bank API
3     Historical  World Bank API
4     Historical  World Bank API
...          ...             ...
5199  Historical  World Bank API
5200  Historical  World Bank API
5201  Historical  World Bank API
5202  Historical  World Bank API
5203  Historical  World Bank API

[5204 rows x 7 columns]
      Year      Country ISO3  GDP_Growth_Percent  Inflation_Percent  \
0     2001  Afghanistan  AFG           -9.431974                NaN
1     2002  Afghanistan  AFG           28.600001                NaN
2     2003  Afghanistan  AFG            8.832278                NaN
3     2004  Afghanistan  AFG            1.414118                NaN
4     2005  Afghanistan  AFG           11.229715          12.686269
...    ...          ...  ...                 ...                ...
5199  2020     Zimbabwe  ZWE           -7.816951         557.201817
5200  2021     Zimbabwe  ZWE            8.468017          98.546105
5201  2022     Zimbabwe  ZWE            6.139263         104.705171
5202  2023     Zimbabwe  ZWE            5.350869         104.705171
5203  2024     Zimbabwe  ZWE            1.742395         104.705171

       Data_Type          Source
0     Historical  World Bank API
1     Historical  World Bank API
2     Historical  World Bank API
3     Historical  World Bank API
4     Historical  World Bank API
...          ...             ...
5199  Historical  World Bank API
5200  Historical  World Bank API
5201  Historical  World Bank API
5202  Historical  World Bank API
5203  Historical  World Bank API

[5204 rows x 7 columns]
      Year      Country ISO3  GDP_Growth_Percent  Inflation_Percent  \
0     2001  Afghanistan  AFG           -9.431974          12.686269
1     2002  Afghanistan  AFG           28.600001          12.686269
2     2003  Afghanistan  AFG            8.832278          12.686269
3     2004  Afghanistan  AFG            1.414118          12.686269
4     2005  Afghanistan  AFG           11.229715          12.686269
...    ...          ...  ...                 ...                ...
5199  2020     Zimbabwe  ZWE           -7.816951         557.201817
5200  2021     Zimbabwe  ZWE            8.468017          98.546105
5201  2022     Zimbabwe  ZWE            6.139263         104.705171
5202  2023     Zimbabwe  ZWE            5.350869                NaN
5203  2024     Zimbabwe  ZWE            1.742395                NaN

       Data_Type          Source
0     Historical  World Bank API
1     Historical  World Bank API
2     Historical  World Bank API
3     Historical  World Bank API
4     Historical  World Bank API
...          ...             ...
5199  Historical  World Bank API
5200  Historical  World Bank API
5201  Historical  World Bank API
5202  Historical  World Bank API
5203  Historical  World Bank API

[5204 rows x 7 columns]

## 3.重复数据的处理

In [5]:
data = {
    "name":['Alice','Alice','Bob','Alice','Jack','Bob'],
    "age":[26,25,30,25,45,30],
    "city":['NY',"NY",'LA','NY','SF','LA']
}
df_3 = pd.DataFrame(data)
print(df_3)

    name  age city
0  Alice   26   NY
1  Alice   25   NY
2    Bob   30   LA
3  Alice   25   NY
4   Jack   45   SF
5    Bob   30   LA

In [6]:
# 检测是否重复
print(df_3.duplicated())
df_3_1 = df_3.drop_duplicates()    # 通过subset参数来根据指定列去重
print(df_3_1)
df_3_2 = df_3.drop_duplicates(subset=['name'],keep='last')    # 通过keep参数来保留以name为依据最后一次出现的行
print(df_3_2)

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool
    name  age city
0  Alice   26   NY
1  Alice   25   NY
2    Bob   30   LA
4   Jack   45   SF
    name  age city
3  Alice   25   NY
4   Jack   45   SF
5    Bob   30   LA

In [7]:
# 数据类型的转换
df_gdp_00_24 = pd.read_csv("data/global_gdp_inflation_2000_2024.csv")
print(df_gdp_00_24.dtypes)
df_gdp_00_24['Year']=df_gdp_00_24['Year'].astype('int16')    # 用.astype(目标类型)
print(df_gdp_00_24.dtypes)

Year                    int64
Country                object
ISO3                   object
GDP_Growth_Percent    float64
Inflation_Percent     float64
Data_Type              object
Source                 object
dtype: object
Year                    int16
Country                object
ISO3                   object
GDP_Growth_Percent    float64
Inflation_Percent     float64
Data_Type              object
Source                 object
dtype: object

关于astype和dtype

dtype的本质是标出数据类型，因此你可以用dtype查看已有数据的数据类型，也可以在创建一个ndarray或者Series时用dtype指定你创建的数据的数据类型

astype则是在事后，把一个数据从原本的类型变换成另一个类型

## 4.数据变形

In [8]:
data_4={
    'ID':[101,102],
    'name':['Alice','Bob'],
    'math':[90,85],
    'English':[88,92],
    'Science':[95,89]
}
df_4=pd.DataFrame(data_4)
print(df_4)

    ID   name  math  English  Science
0  101  Alice    90       88       95
1  102    Bob    85       92       89

In [9]:
# 最简单的变形：转置
print(df_4.T)

             0    1
ID         101  102
name     Alice  Bob
math        90   85
English     88   92
Science     95   89

In [10]:
# 使用pd.melt()函数可以对df进行如下变形，把宽表变成长表，从而把原本的列名变成数据。
df_4_1=pd.melt(df_4,id_vars=['ID','name'],var_name='科目',value_name='分数')
# 宽表在分组统计中常用，且容易被机器识别。其中各个参数：
# id_vars → 保留的列，不做变化（ID和name）
# var_name → 原列名变成哪一列（各个学科变成"科目"这一列，原来的'math''English'等作为数据填入这一列）
# value_name → 原数值变成哪一列，各科成绩填入"分数"这一列

df_4_2=df_4_1.sort_values('name')
print(df_4_2)

    ID   name       科目  分数
0  101  Alice     math  90
2  101  Alice  English  88
4  101  Alice  Science  95
1  102    Bob     math  85
3  102    Bob  English  92
5  102    Bob  Science  89

In [11]:
# pd.pivot, 则是melt的逆操作，把长表变成宽表。
df_4_3=pd.pivot(df_4_1,index=['ID','name'],columns='科目',values='分数')
# index和columns很好理解，values是指用原先的宽表里的哪一列中的数据来填充
print(df_4_3)

科目         English  Science  math
ID  name
101 Alice       88       95    90
102 Bob         92       89    85

In [12]:
# 分列操作
data_4={
    'ID':[101,102],
    'name':['Alice Smith','Bob Smith'],
    'math':[90,85],
    'English':[88,92],
    'Science':[95,89]
}
df_4=pd.DataFrame(data_4)
df_4[['First_name','Last_name']]=df_4['name'].str.split(" ",expand=True)
                                             # ^ 这里的.str是指把对象当作字符串进行处理
# 其中expand参数的含义
# expand=False（默认）：返回 Series，每个元素是一个列表 ['Alice', 'Smith']
# expand=True：返回 DataFrame，将列表元素拆成多列
print(df_4)

    ID         name  math  English  Science First_name Last_name
0  101  Alice Smith    90       88       95      Alice     Smith
1  102    Bob Smith    85       92       89        Bob     Smith

## 5.数据分箱

In [13]:
df_5=pd.read_csv('data/student_academic_performance.csv')
df_5.head(25)

,Student ID,Gender,Race/Ethnicity,Parental Education,Lunch Type,Test Preparation,Study Time per Week,Daily Sleep Duration,Math Score,Reading Score,Writing Score,School Type,Internet Access
0,1,female,group B,some college,standard,False,12.4,5.4,62.0,76.0,65.0,public,True
1,2,male,group D,high school,standard,False,18.3,5.1,74.0,73.0,76.0,public,NaN
2,3,male,group B,bachelor degree,free/reduced,True,11.8,7.8,71.0,83.0,91.0,public,False
3,4,male,group E,high school,standard,False,NaN,7.3,83.0,73.0,52.0,public,True
4,5,female,group C,bachelor degree,standard,True,12.9,6.3,41.0,NaN,81.0,public,True
5,6,female,group E,associate degree,standard,False,10.1,6.4,67.0,NaN,83.0,public,True
6,7,female,group E,some college,standard,False,NaN,4.7,51.0,NaN,81.0,public,True
7,8,male,group B,some college,standard,False,11.1,7.0,65.0,86.0,79.0,private,True
8,9,male,group C,bachelor degree,standard,False,3.8,7.0,63.0,66.0,78.0,international,False
9,10,female,group B,bachelor degree,free/reduced,False,15.0,7.3,70.0,82.0,51.0,public,False
10,11,female,group E,some college,free/reduced,True,11.3,NaN,82.0,76.0,NaN,private,True
11,12,female,group E,some college,free/reduced,True,8.9,9.7,35.0,48.0,59.0,public,True
12,13,male,group E,bachelor degree,standard,False,18.4,6.4,66.0,52.0,79.0,public,NaN
13,14,male,group D,high school,free/reduced,False,6.9,8.6,68.0,61.0,NaN,public,True
14,15,male,group C,some college,standard,True,6.9,8.2,80.0,78.0,78.0,public,True
15,16,male,group C,associate degree,standard,True,20.5,6.7,61.0,93.0,77.0,public,True
16,17,female,group B,some college,standard,False,8.3,NaN,90.0,74.0,68.0,private,True
17,18,female,group D,some college,free/reduced,False,15.9,9.2,75.0,62.0,73.0,public,True
18,19,male,group C,master degree,free/reduced,True,5.0,6.1,57.0,NaN,80.0,public,True
19,20,female,group B,master degree,standard,True,10.2,7.0,78.0,66.0,83.0,private,True
20,21,female,group B,high school,standard,True,12.6,8.6,93.0,45.0,68.0,international,True
21,22,male,group A,NaN,standard,True,13.0,7.7,54.0,NaN,95.0,public,True
22,23,female,group D,associate degree,standard,False,21.0,8.3,34.0,73.0,94.0,public,False
23,24,female,group D,bachelor degree,NaN,False,8.9,6.1,77.0,93.0,90.0,private,True
24,25,male,group C,master degree,standard,False,3.7,6.9,46.0,84.0,67.0,international,False

In [14]:
df_5_1 = df_5.head(10)[['Student ID','Math Score']]
df_5_1

   Student ID  Math Score
0           1        62.0
1           2        74.0
2           3        71.0
3           4        83.0
4           5        41.0
5           6        67.0
6           7        51.0
7           8        65.0
8           9        63.0
9          10        70.0

In [15]:
# 使用pd.cut()来进行分箱操作
pd.cut(df_5_1['Math Score'],bins=2)
# bins如果是一个整数num，就代表着把指定的某一列所有数值数据分为num个区间，输出结果为各个原数据所在的区间。
# 其中起始值和结束值为所有数据的min（实际上会比min小一点点）和max
pd.cut(df_5_1['Math Score'],bins=[40,50,60,70,80,90],labels=['F','E','D','C','B'])
# bin也可以这样写成list，同样表示分箱的各个区间
# labels就是给每个区间起的名字。如果有labels参数，输出结果就会是labels，可读性更高。
# 需要注意的是，labels的数据类型是 Categorical 类型。

# 分完箱以后，我们可以把分箱结果作为新的列填回原表
df_5_1['Math Score Level']=pd.cut(df_5_1['Math Score'],bins=[40,50,60,70,80,90,100],labels=['F','E','D','C','B','A'])
df_5_1

   Student ID  Math Score Math Score Level
0           1        62.0                D
1           2        74.0                C
2           3        71.0                C
3           4        83.0                B
4           5        41.0                F
5           6        67.0                D
6           7        51.0                E
7           8        65.0                D
8           9        63.0                D
9          10        70.0                D

有关Categorical这一数据类型的介绍

对于一些在数据分析中数量有限且重复出现的数据，例如成绩分级A-F，性别，病期I-IV期等等，如果全部使用字符串即object来表示，会占用过多性能

通过astype()方法把这些数据变为pandas.Categorical类型，可以有效降低性能损耗，原理类似于把字符串比较转变为更简单的整数比较

需要注意的是，对于Category这一类型的处理，pandas有专门的一套方法名，因此在套用其他一些普适性比较广的方法名（如去重去NaN等）时请先考虑是否会导致原有的Category造成变化。

具体的方法请见《利用Python进行数据分析》的233页表7-7

In [16]:
# pd.qcut()可以进行等频率的分割，在本案例中会让每个区间里的人数相等
pd.qcut(df_5_1['Math Score'],2)    # 这个整数参数同样表示分为几个区间
pd.qcut(df_5_1['Math Score'],2).value_counts()    #.value_counts()可以算出每个区间有多少个数据，和后面groupby的.size()很像

Math Score
(40.999, 66.0]    5
(66.0, 83.0]      5
Name: count, dtype: int64

In [17]:
df_5_2=df_5.head(25)[['Student ID','Math Score']]

df_5_2['Math_Score_Level']=pd.cut(df_5_2['Math Score'],bins=[0,50,60,70,80,90,100],labels=['F','E','D','C','B','A'])
# 可以发现，用list来表示bins参数的区间不一定需要每个区间等长
df_5_2

    Student ID  Math Score Math_Score_Level
0            1        62.0                D
1            2        74.0                C
2            3        71.0                C
3            4        83.0                B
4            5        41.0                F
5            6        67.0                D
6            7        51.0                E
7            8        65.0                D
8            9        63.0                D
9           10        70.0                D
10          11        82.0                B
11          12        35.0                F
12          13        66.0                D
13          14        68.0                D
14          15        80.0                C
15          16        61.0                D
16          17        90.0                B
17          18        75.0                C
18          19        57.0                E
19          20        78.0                C
20          21        93.0                A
21          22        54.0                E
22          23        34.0                F
23          24        77.0                C
24          25        46.0                F

## 6.时间数据的处理

In [18]:
# 时间戳
d = pd.Timestamp('2026-02-28 18:53:37')
print(d)
print(type(d))
print('年：',d.year)
print('月：',d.month)
print('日：',d.day)
print('季度：',d.quarter)
print('是否是月初：',d.is_month_start)
print('是否是月底：',d.is_month_end)

2026-02-28 18:53:37
<class 'pandas._libs.tslibs.timestamps.Timestamp'>
年： 2026
月： 2
日： 28
季度： 1
是否是月初： False
是否是月底： True

In [19]:
# 方法
print('这一天是：',d.day_name())
print('以天为最小周期：',d.to_period('D'))
print('以季度为最小周期：',d.to_period('Q'))
# 年度为Y，月度为M，周维度为W

这一天是： Saturday
以天为最小周期： 2026-02-28
以季度为最小周期： 2026Q1

In [20]:
# 字符串转换为日期类型
a = '2026-02-25'
b = pd.to_datetime(a)
print(type(a))
print(type(b))

# DataFrame转换为日期类型
df_6 = pd.DataFrame({
    'sales':[100,200,300],
    'date':['20260223','20260224','20260225']     # 注意，日期的原数据类型得是字符串。如果是数字，结果不会符合你的预期的。
})
df_6['datetime']=pd.to_datetime(df_6['date'])
print(df_6)
# 这里是把df_6['datetime']里的原数据变成了Timestamp类型，而其本身是一个Series
print(type(df_6['datetime']))
df_6['Week']=df_6['datetime'].dt.day_name()
print(df_6)

<class 'str'>
<class 'pandas._libs.tslibs.timestamps.Timestamp'>
   sales      date   datetime
0    100  20260223 2026-02-23
1    200  20260224 2026-02-24
2    300  20260225 2026-02-25
<class 'pandas.core.series.Series'>
   sales      date   datetime       Week
0    100  20260223 2026-02-23     Monday
1    200  20260224 2026-02-24    Tuesday
2    300  20260225 2026-02-25  Wednesday

In [21]:
# csv的日期转换
df_6_1 = pd.read_csv('data/tech_employment_2000_2025.csv')
df_6_1['year'] = pd.to_datetime(df_6_1['year'])
df_6_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 532 entries, 0 to 531
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   company                   532 non-null    object
 1   year                      532 non-null    datetime64[ns]
 2   employees_start           532 non-null    int64
 3   employees_end             532 non-null    int64
 4   new_hires                 532 non-null    int64
 5   layoffs                   532 non-null    int64
 6   net_change                532 non-null    int64
 7   hiring_rate_pct           532 non-null    float64
 8   attrition_rate_pct        532 non-null    float64
 9   revenue_billions_usd      532 non-null    float64
 10  stock_price_change_pct    532 non-null    float64
 11  gdp_growth_us_pct         532 non-null    float64
 12  unemployment_rate_us_pct  532 non-null    float64
 13  is_estimated              532 non-null    bool
 14  confidence_level          532 non-null    object
 15  data_quality_score        532 non-null    int64
dtypes: bool(1), datetime64[ns](1), float64(6), int64(6), object(2)
memory usage: 63.0+ KB

In [22]:
# 时间间隔
d1 = pd.Timestamp('2006-07-03')
d2 = pd.Timestamp('2026-02-26')
d3 = d2-d1
print(d3)
print(type(d3))    # d3的数据类型为Timedelta, 时间间隔
# 时间序列
days = pd.date_range('2025-07-03','2026-02-26',freq='D')
print(days)    # 会生成一个日期序列，你可以自定义freq（类似于步长）
days_1 = pd.date_range('2025-07-03',periods=15,freq='W')    # 还可以这样写
print(days_1)

7178 days 00:00:00
<class 'pandas._libs.tslibs.timedeltas.Timedelta'>
DatetimeIndex(['2025-07-03', '2025-07-04', '2025-07-05', '2025-07-06',
               '2025-07-07', '2025-07-08', '2025-07-09', '2025-07-10',
               '2025-07-11', '2025-07-12',
               ...
               '2026-02-17', '2026-02-18', '2026-02-19', '2026-02-20',
               '2026-02-21', '2026-02-22', '2026-02-23', '2026-02-24',
               '2026-02-25', '2026-02-26'],
              dtype='datetime64[ns]', length=239, freq='D')
DatetimeIndex(['2025-07-06', '2025-07-13', '2025-07-20', '2025-07-27',
               '2025-08-03', '2025-08-10', '2025-08-17', '2025-08-24',
               '2025-08-31', '2025-09-07', '2025-09-14', '2025-09-21',
               '2025-09-28', '2025-10-05', '2025-10-12'],
              dtype='datetime64[ns]', freq='W-SUN')

## 7.分组聚合

In [24]:
# df.groupby('分组的字段')['聚合的字段'].聚合函数()
df_7 = pd.read_csv('data/student_academic_performance.csv')

# 先看看这个csv的基本情况
#print(df_7.isna().sum())
#print(df_7.dtypes)

# 剔除空值，并且对一些数据进行适当的转化以节约性能
df_7 = df_7.fillna({
    'Parental Education':'UNKNOWN',
    'Lunch Type':'UNKNOWN',
    'Study Time per Week':df_7['Study Time per Week'].mean(),
    'Daily Sleep Duration':df_7['Daily Sleep Duration'].mean(),
    'Reading Score':df_7['Reading Score'].mean(),
    'Writing Score':df_7['Writing Score'].mean()
})    # 剩下两个列的数据种类为布尔值，这两个列里的缺失值该如何处理呢？

df_7[['Math Score','Reading Score','Writing Score']] = df_7[['Math Score','Reading Score','Writing Score']].astype('int64')

df_7[['Gender','Race/Ethnicity','Parental Education','Lunch Type','School Type']] = df_7[['Gender','Race/Ethnicity','Parental Education','Lunch Type','School Type']].astype('category')

#print(df_7.groupby(['Parental Education']).size())    # .size()方法可以返回一个含有各个分组大小的Series，书上说很实用（思考
# 另外这一行还有FutureWarning

# 这个分组聚合具体怎么使用呢？其实在我们这个案例里就非常合适。
# 比如，根据父母的受教育程度以及学校类型不同，我们可以对受测试的学生进行分组，并按照分组计算不同分组的成绩平均值
# 可以通过列表一次性传入多个分组的参考列名，专业叫法为：键
grouped1 = df_7.groupby(['Parental Education','School Type'],observed=True)['Math Score']
# 参数observed是什么意思？当你对categorical列分组时：Pandas默认行为（observed=False)是：即使某个类别在数据中没有出现，也会显示出来。
#print(grouped1.mean())
#print(df_7.dtypes)

# 如果要统计比较多的值，例如按照前面的分组，给Math Score算平均值，给Internet Access算众数。可以使用.agg({'列名':'方法名',...})
grouped2 = df_7.groupby(['Parental Education','School Type'],observed=True).agg({
    'Math Score':'mean',
    'Reading Score':'mean',
    'Internet Access':'mean'    # 还记得True=1,False=0吗？对这个布尔Series求平均值，就可以算出True在当中所占的比例了
})
print(grouped2)

                                  Math Score  Reading Score Internet Access
Parental Education School Type
UNKNOWN            international   67.492958      71.422535        0.869565
                   private         68.022059      69.161765        0.852941
                   public          69.764706      71.040568        0.892704
associate degree   international   70.115385      70.307692        0.862745
                   private         69.846473      71.211618        0.854701
                   public          69.161376      71.066138           0.875
bachelor degree    international   71.106557      72.967213        0.827586
                   private         70.217228      71.853933        0.883721
                   public          69.567010      70.979381        0.876351
high school        international   68.994845      71.056701        0.867021
                   private         69.413793      70.985222        0.877863
                   public          69.489960      70.939759        0.877946
master degree      international   69.045455      70.431818        0.904762
                   private         68.984848      71.636364        0.851562
                   public          69.581340      70.956938        0.840796
some college       international   69.554054      71.128378        0.852113
                   private         69.788591      69.755034        0.868056
                   public          69.326046      71.926806        0.871921